<?php

/*
 *  Read file
 */

$data=file($argv[1]);
$array=array(); // associative array
$keys=array();  // indexed array

echo "FileSize is: " .filesize($argv[1])." bytes\n";

/*
 * Since, file is generated by us, we have key=>Value pair.
 * Storing it in associative array.So that we can later on use it with 'Memcached'
 */

foreach($data as $line)
{
	$kv = explode(": ",$line); // Since, script is written in such a way for generating data
	
	array_push($keys, $kv[0]); // Also, storing keys. This will be useful while retrieving data frim 'Memcached' Database
	$array[$kv[0]] = $kv[1];
}

/*
 *  Lets dump keys to another file, useful for 'searching'. 
 *  Since, I have wriiten another file for reading/searching.
 */

$string_data = serialize($keys);
file_put_contents("mem_keys.txt", $string_data);

/*
 * Create Memcached Instance here
 */

$mc = new Memcached();
$mc->addServer("127.0.0.1", 11211);

/*
 *  Adding to memcached server
 */

$count=0;
foreach($array as $key => $value)
{
	$mc->set($key, $value);
	if($mc->getResultCode() != 0)
	{
		echo "Not Stored ErroCode ".$mc->getResultCode()."\n";
		return;
	}
	else if($mc->getResultCode() == 0)
	{
	//	echo "Successs.. \n";
	}

	$count++;
}

echo "$count keys written to Memcache";

?>
